# Generated by Django 3.2.7 on 2021-09-12 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='url',
        ),
        migrations.AddField(
            model_name='issue',
            name='api_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='API URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='html_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='HTML URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='api_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='API URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='html_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='HTML URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='api_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='API URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='html_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='HTML URL'),
            preserve_default=False,
        ),
    ]
