# Generated by Django 3.2.7 on 2021-09-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210912_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
    ]
