# Generated by Django 3.2.7 on 2021-09-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_issue_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending Verification')], default=3, verbose_name='State'),
        ),
    ]
