# Generated by Django 3.2.7 on 2021-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_pullrequest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_restricted',
            field=models.BooleanField(default=False, verbose_name='Is Restricted'),
        ),
    ]
