# Generated by Django 3.2.7 on 2021-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_issueassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueassignment',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Decided At'),
        ),
    ]
