# Generated by Django 3.2.7 on 2021-09-14 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0010_issueassignment_decided_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueAssignment',
            new_name='IssueAssignmentRequest',
        ),
    ]
