# Generated by Django 3.2.7 on 2021-09-14 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210914_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeissue',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Decided At'),
        ),
    ]
