# Generated by Django 3.2.7 on 2021-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_activeissue_assigned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assignee',
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (3, 'Closed')], default=1, verbose_name='State'),
        ),
    ]
