# Generated by Django 3.2.7 on 2021-09-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210914_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequest',
            name='api_url',
        ),
    ]
