# Generated by Django 3.2.7 on 2021-09-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_pullrequest_api_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequest',
            old_name='user',
            new_name='contributor',
        ),
    ]
