# Generated by Django 3.2.7 on 2021-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_pullrequest_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1, verbose_name='Level'),
        ),
    ]
