# Generated by Django 3.2.7 on 2021-09-23 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_issue_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeissue',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned At'),
        ),
    ]
