# Generated by Django 3.2.7 on 2021-09-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_project_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Free'), (4, 'Very-Easy'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1, verbose_name='Level'),
        ),
    ]
