# Generated by Django 3.2.8 on 2021-10-09 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_alter_issue_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueassignmentrequest',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
