# Generated by Django 4.1 on 2022-10-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_alter_issue_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SubDomain'),
        ),
    ]
