# Generated by Django 4.1 on 2022-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_domain_subdomain_remove_project_subdomain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subdomain',
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='project',
            name='Subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SubDomain'),
        ),
    ]
