# Generated by Django 4.1 on 2022-10-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_remove_project_subdomain_alter_project_domain_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='SubDomain',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Subdomain',
            new_name='subdomain',
        ),
    ]
