# Generated by Django 4.1 on 2022-10-08 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_domain_subdomain_alter_project_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subdomain',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='project.subdomain'),
        ),
    ]
