# Generated by Django 4.1 on 2022-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_alter_project_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
