# Generated by Django 4.1 on 2022-10-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0036_alter_project_subdomain_alter_subdomain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="remark",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="remark"
            ),
        ),
    ]
