# Generated by Django 4.1 on 2022-10-15 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_issue_dislikes_issue_likes_like_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueassignmentrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Requested At'),
        ),
    ]
