# Generated by Django 3.2.7 on 2021-10-16 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0039_alter_pullrequest_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
