# Generated by Django 3.2.7 on 2021-10-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_alter_pullrequest_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bonus_description',
            field=models.CharField(default='NA', max_length=400, verbose_name='bonus_description'),
        ),
        migrations.AddField(
            model_name='issue',
            name='have_bonus',
            field=models.BooleanField(default=False, verbose_name='Have Bonus'),
        ),
    ]
