# Generated by Django 3.2.20 on 2023-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_issue_bonus_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='levelcolor',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (4, ''), (1, 'green'), (2, 'yellow'), (3, 'red')], default=1, verbose_name='Level Color'),
        ),
    ]
