# Generated by Django 4.1 on 2024-10-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_issue_levelcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mentor',
            field=models.CharField(default=None, max_length=200, verbose_name='Mentor'),
        ),
        migrations.AddField(
            model_name='project',
            name='mentor_url',
            field=models.URLField(default=None, verbose_name='MENTOR URL'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='levelcolor',
            field=models.PositiveSmallIntegerField(choices=[(0, '#f2f2f2'), (4, '#39c0ed'), (1, '#00b74a'), (2, '#ffa900'), (3, '#f93154')], default=1, verbose_name='Level Color'),
        ),
    ]
