# Generated by Django 3.2.7 on 2021-10-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20211018_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='bonus_description',
        ),
    ]
