# Generated by Django 3.2.7 on 2021-10-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_project_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='sub_domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='name',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
