# Generated by Django 3.2.7 on 2021-10-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_alter_project_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain',
        ),
    ]
