# Generated by Django 4.1 on 2024-10-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_project_mentor_project_mentor_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='Project Description'),
        ),
    ]
