# Generated by Django 4.1 on 2025-10-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_alter_issue_levelcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.URLField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='homepage',
            field=models.URLField(blank=True, verbose_name='Homepage'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Pushed At'),
        ),
        migrations.AddField(
            model_name='project',
            name='topics_raw',
            field=models.TextField(blank=True, verbose_name='Topics'),
        ),
    ]
