# Generated by Django 3.2.7 on 2021-10-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_auto_20211019_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain',
        ),
    ]
