# Generated by Django 3.2.7 on 2021-10-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_remove_project_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.RemoveField(
            model_name='subdomain_project_model',
            name='project',
        ),
        migrations.RemoveField(
            model_name='subdomain_project_model',
            name='sub_domain',
        ),
        migrations.DeleteModel(
            name='SubDomain',
        ),
        migrations.DeleteModel(
            name='SubDomain_Project_Model',
        ),
    ]
