# Generated by Django 4.1 on 2024-10-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Project Description'),
        ),
    ]
