# Generated by Django 3.2.7 on 2021-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_auto_20211019_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain'),
        ),
    ]
