# Generated by Django 4.1 on 2024-10-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.CharField(default='hex', max_length=200, verbose_name='Mentor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor_url',
            field=models.URLField(default='', verbose_name='MENTOR URL'),
        ),
    ]
