# Generated by Django 3.2.7 on 2021-10-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]