# Generated by Django 3.2.7 on 2021-10-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_project_all_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='all_tech',
        ),
    ]
