# Generated by Django 3.2.7 on 2021-09-09 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='student', max_length=10, verbose_name='user_role')),
                ('issues_solved', models.IntegerField(default=0, verbose_name='issues_solved')),
                ('total_points', models.IntegerField(default=0, verbose_name='points')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='bonus_points')),
                ('deducted_points', models.IntegerField(default=0, verbose_name='deducted_points')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
