# Generated by Django 3.2.7 on 2021-09-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(default=1, verbose_name='user_role'),
        ),
    ]
