# Generated by Django 3.2.7 on 2021-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Mentor'), (3, 'Admin')], default=1, verbose_name='user_role'),
        ),
    ]
