# Generated by Django 3.2.7 on 2021-09-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is Complete'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bonus_points',
            field=models.IntegerField(default=0, verbose_name='Bonus Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deducted_points',
            field=models.IntegerField(default=0, verbose_name='Deducted Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='issues_solved',
            field=models.IntegerField(default=0, verbose_name='Issues Solved'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Mentor'), (3, 'Admin')], default=1, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
    ]
