# Generated by Django 4.1 on 2022-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_userprofile_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ms_teams_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_id',
            field=models.URLField(default='', verbose_name='Linkedin ID'),
        ),
    ]
