# Generated by Django 3.2.7 on 2021-10-12 10:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_userprofile_whatsapp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='whatsapp no'),
        ),
    ]
